config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
#mise en place de la route pour compléter le formulaire d'inscription ) l'évenement par CB
  post "events/subscribe/:id", to: "events#subscribe", as: "subscription"
  devise_for :users
  resources :attendances
  resources :users 
  resources :events do
  	resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
		has_many :attendances	
		has_one_attached :avatar


		#la ligne du bas est enlevée
		#has_many :guests, through: :attendances

		belongs_to :admin, class_name: "User"

 		# La date de début est obligatoire et il est impossible de créer un événement dans le passé
	    validates :start_date, presence: true
		#validate :expiration_date_cannot_be_in_the_past

 		# Le titre est obligatoire et doit faire entre 5 et 140 caractères
		validates :title, presence: true,
		length: {in: 5..140}

		# La description est obligatoire et doit faire entre 20 et 1000 caractères 
 		validates :description, presence: true, length: {in: 20..1000}
 

 		# Le prix est obligatoire et compris entre 1 et 1000
		validates :price, presence: true,
		inclusion: {in: 1..1000}

		validates :location, presence: true

		# La durée est obligatoire et la durée doit être strictement positive et un multiple de 5
		 validates :duration, presence: true, numericality: { only_integer: true }
		# :divisible_by_five


  def expiration_date_cannot_be_in_the_past
    if expiration_date.present? && expiration_date.past?
      errors.add(:start_date, "can't be in the past")
    end
  end    






    def divisible_by_five
      unless duration%5 == 0
        self.errors.add(:duration, "is not divisible by 5")
      end
    end
 
 




 end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index] 





  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
 
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)
    @event.admin_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def subscribe
    @event = Event.find(params[:id])
    #vérifie que le participant n'est pas déjà inscrit ou bien n'est pas l'organisateur
    if
    Attendance.where(guest_id: current_user.id, event_id: @event.id).exists?
    flash[:error] = "Vous participez déjà à l'événement !" 
    redirect_to @event
    end

#sinon, déclenche le formulaire pris en ligne sur Stripe avec infos CB

    @amount =  @event.price

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )


    charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'eur'
   )

   @attendance = Attendance.create(stripe_customer_id: rand(200..1000), guest_id: current_user.id, event_id: @event.id)
      puts 
      flash[:success] = "Vous participez à l'événement !" 
      redirect_to @event


#affiche les erreurs si numéro de CB inexistant par exemple
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <input class="btn btn-outline-info" type="submit" value="Submit">
  </div>

<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: "btn btn-primary" %>
<%= link_to 'Show', @event, class: "btn btn-success" %>
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/events/index.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Bienvenue sur tous les events!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">Inscris-toi! &raquo;</a></p>
        </div>
      </div>





      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <% @events.each do |event| %>
            <div class="col-md-4 mb-4" >
              <%if event.avatar.attached?%>
              <p><%= image_tag event.avatar, alt: 'avatar' %></p>
              <% end %>
              <h2><%= event.title %></h2>
              <p><%= event.start_date %></p>
              <p>Duration: <%= event.duration %> minutes.</p>
              <p><%= event.description %></p>
              <td>Location: <%= event.location %> - Price: <%= event.price %>€</td></br>
              <td><%= link_to 'Show', event %></td>
            </div>
          <% end%>     
        </div>
        <hr>
      </div>
    </main>

    <footer class="container">
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
   <div style="text-align: center;">
  <p>
    <h1>Page Profil de l'event</h1>

    <%if @event.avatar.attached?%>
      <%= image_tag @event.avatar, alt: 'avatar' %>
    <%else%>
      <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
    <%end%>
    <% if current_user.id == @event.admin_id %>
      <h3>Changer l'avatar de l'event?</h3>
      </br>
      <%= form_tag event_avatars_path(@event), multipart: true do %>
      <%= file_field_tag :avatar %>
      <%= submit_tag "mettre à jour" %>
      <% end %>
    <% end %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= @event.duration %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @event.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @event.location %>
  </p>

  <p>
    <strong>Admin email:</strong>
    <%= User.find(Event.find(@event.id).admin_id).email %>
  </p>

  <p>
    <strong>Number of guests</strong>
    <%= Attendance.where(event_id: @event.id).count %>
  </p>

    <% if current_user.id != @event.admin_id %>
      <div><%= form_tag subscription_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
             <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="amount">
            <p> Pour rejoindre l'événement "<%= @event.title %>", merci de régler la somme de <%= @event.price %>€</p>
          </label>
        </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Payment for - <%= @event.title %> -"
              data-amount="<%= (@event.price.to_f)*100 %>"
              data-currency="eur"
              data-locale="auto"></script> 
      <% end %>
      </div>
    <% else %>
      <p class="text-center">  <%= link_to "My event", { :controller => "attendances", :action => "show"}, class: "btn btn-success" %> </p>
    <% end %>



  <p>
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>
  </p>
</div>